[package]
name = "cook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
cooklang = "0.9"
anyhow = "1"
camino = { version = "1", features = ["serde1"] }
once_cell = "1.17"
cooklang-to-human = "0.9.0"
cooklang-to-cooklang = "0.9.0"
cooklang-to-md = "0.9.0"
serde_json = "1.0.108"
anstream = "0.6.4"
cooklang-fs = "0.9.0"
