name: Cookcli
services:
    cookcli:
        ports:
            - 9080:9080
        network_mode: host
        volumes:
            - ${ROOT}/recipes:/recipes # Recipe storage location
        container_name: cookcli
        restart: always
        image: cookcli:latest
